/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wwc2_networks_server_dvr_jni_DvrDataNative */

#ifndef _Included_com_wwc2_networks_server_dvr_jni_DvrDataNative
#define _Included_com_wwc2_networks_server_dvr_jni_DvrDataNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wwc2_networks_server_dvr_jni_DvrDataNative
 * Method:    openMain
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wwc2_networks_server_dvr_jni_DvrDataNative_openMain
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wwc2_networks_server_dvr_jni_DvrDataNative
 * Method:    openSub
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wwc2_networks_server_dvr_jni_DvrDataNative_openSub
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wwc2_networks_server_dvr_jni_DvrDataNative
 * Method:    closeMain
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wwc2_networks_server_dvr_jni_DvrDataNative_closeMain
  (JNIEnv *, jobject);

/*
 * Class:     com_wwc2_networks_server_dvr_jni_DvrDataNative
 * Method:    closeSub
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wwc2_networks_server_dvr_jni_DvrDataNative_closeSub
  (JNIEnv *, jobject);

/*
 * Class:     com_wwc2_networks_server_dvr_jni_DvrDataNative
 * Method:    getKeyO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_networks_server_dvr_jni_DvrDataNative_getKeyO
  (JNIEnv *, jobject);

/*
 * Class:     com_wwc2_networks_server_dvr_jni_DvrDataNative
 * Method:    getKeyT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_networks_server_dvr_jni_DvrDataNative_getKeyT
  (JNIEnv *, jobject);

/*
 * Class:     com_wwc2_networks_server_dvr_jni_DvrDataNative
 * Method:    getOsStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_networks_server_dvr_jni_DvrDataNative_getOsStatus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
