/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wwc2_networks_cmd_jni_CameraDataSync */

#ifndef _Included_com_wwc2_networks_cmd_jni_CameraDataSync
#define _Included_com_wwc2_networks_cmd_jni_CameraDataSync
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wwc2_networks_cmd_jni_CameraDataSync
 * Method:    openDev
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wwc2_networks_cmd_jni_CameraDataSync_openDev
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wwc2_networks_cmd_jni_CameraDataSync
 * Method:    closeDev
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wwc2_networks_cmd_jni_CameraDataSync_closeDev
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wwc2_networks_cmd_jni_CameraDataSync
 * Method:    blockRead
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_networks_cmd_jni_CameraDataSync_blockRead
  (JNIEnv *, jobject);

/*
 * Class:     com_wwc2_networks_cmd_jni_CameraDataSync
 * Method:    blockWrite
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wwc2_networks_cmd_jni_CameraDataSync_blockWrite
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
